# Site settings
title: "My Resume"
description: "Resume for Brett Lambert in a simple yet elegant jekyll format."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Brett Lambert"
resume_title:                   "Building Automation Professional"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mrbrettlambert@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "xxx-xxx-xxxx"
resume_contact_address:         "1234 Sesame St."

resume_header_contact_info:     "address • phone # • mrbrettlambert@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I have been traveling my career path in the HVAC/Building Controls industry since 1998.  I have a vast working knowledge of many different control platforms, the theory behind the industry, and design of energy efficent systems. I feel that my talent, skills, and experience would be a great asset to a growing and forward thinking building contol team.  I am highly adpet with integration of multiple protocols and platforms which is an absolute need in this constantly changing field. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/brettnreno/resume"
#  resume_twitter_url:           "http://twitter.com/"
#  resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
#  resume_linkedin_url:          "https://www.linkedin.com/in/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://brettlambert.online"
#  resume_medium_url:            "https://medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-minimal